

class ParaKeys:
	
	ISFILESEARCH = "ISFILESEARCH"
	FILETYPESLIST = "FILETYPESLIST"
	LOGININFOS = "LOGININFOS"
	FILESTARTURL = "FILESTARTURL"
	SQLSTARTURL = "SQLSTARTURL"
	KEYWORDS = "KEYWORDS"
	RESULTQUEUE = "RESULTQUEUE"
	FLAGQUEUE = "FLAGQUEUE"
	PAUSEEVENT = "PAUSEEVENT"